### ISSUE TITLE
Breaking change with 1.0.0 beta, but what is it?

### ISSUE THREAD

**Issue by StephanBijzitter** [webpack-contrib/i18n-webpack-plugin#50] opened 2017-05-16 10:55 UTC
```
Module parse failed: /vagrant/node_modules/babel-loader/lib/index.js!/vagrant/node_modules/ts-loader/index.js!/vagrant/src/business/Intent/Intent.ts _this.evaluateExpression is not a function
You may need an appropriate loader to handle this file type.
TypeError: _this.evaluateExpression is not a function
    at Parser.<anonymous> (/vagrant/node_modules/i18n-webpack-plugin/dist/index.js:94:31)
    at Parser.applyPluginsBailResult1 (/vagrant/node_modules/tapable/lib/Tapable.js:120:27)
    at Parser.walkCallExpression (/vagrant/node_modules/webpack/lib/Parser.js:1096:19)
```

I just upgraded from `0.3.0` to `1.0.0-beta.0` and restarted webpack-dev-server to see this error in the console. Note that this was the only change made to trigger this error; no code was changed.

It seems it's crashing on the file because it's a typescript file, but `0.3.0` had no problems here, so I'm wondering if this change is an accidental bug in `1.0.0`. If you could point me into the right direction, I might be able solve this issue in a PR, but it'll also be a new experience for me :-)

Using webpack 2.5.1, webpack-dev-server 2.4.5 and NodeJS 6.10.3

**Comment by hovissimo** [comment] 2017-05-19 03:20
I got this error with the beta as well, same trace, but I don't use typescript.

Webpack 2.2.1, NodeJS 6.9.1

**Comment by evilebottnawi** [comment] 2017-05-19 10:10
@StephanBijzitter @hovissimo guys, can your create minimal test reproducible test repo?

**Comment by d3viant0ne** [comment] 2017-05-19 20:12
@StephanBijzitter - `1.0.0-beta` doesn't technically change functionality, it does update everything to ES2016+ so this is definitely a bug of some sort.

Anything public where that I can get into a debugger would be super helpful to get this addressed.

**Comment by StephanBijzitter** [comment] 2017-05-20 15:59
I'll try to set up a repository with minimal code to reproduce on Monday!

**Comment by hovissimo** [comment] 2017-05-30 22:03
I'm having trouble reproducing this in a fresh project.

@StephanBijzitter Can you post your dependencies at least, so I can look for common dependencies in our projects?

**Comment by msholty-fd** [comment] 2017-06-06 20:58
I think the issue is because of `_this` not being the correct `this`, because of this:
https://github.com/webpack-contrib/i18n-webpack-plugin/blob/master/src/index.js#L48

`i18nPlugin` is not an arrow function, so when compiled down, `this.evaluateExpression` changes to `_this.evaluateExpression` and it's not there.

Go into the compiled code (`dist/index.js`) and change all instances of `_this` to `this` and you'll see the issues go away. I don't know exactly how to fix this, because it looks like it was an intentional thing to not use an arrow function here.

**Comment by d3viant0ne** [comment] 2017-06-06 21:22
Sorry guys, busy last week. Working on this right now.

**Comment by d3viant0ne** [comment] 2017-06-06 21:49
@hovissimo @StephanBijzitter  - Pick up `1.0.0-beta.1`, problem is resolved in the project Hovis provided. If anyone else has an issue, ping me on Twitter ( goes to my phone ) so I can get it addressed. I'd like to get a single rc version out and hopefully on the dist-tag by end of week.

![screen shot 2017-06-06 at 4 46 41 pm](https://user-images.githubusercontent.com/8420490/26853486-d1860b64-4ad7-11e7-92df-569746c3f849.png)

**Comment by StephanBijzitter** [comment] 2017-06-06 21:55
Will try tomorrow! Promise!
(will edit with results)

**Comment by msholty-fd** [comment] 2017-06-07 12:55
@d3viant0ne I had the issues reported in this thread, and I tested with `1.0.0-beta.1`. I don't see any problems now. Thanks a lot!

**Comment by d3viant0ne** [comment] 2017-06-07 15:52
@msholty-fd - No problem, will hold off on resolving it until I hear back from Stephan.

**Comment by StephanBijzitter** [comment] 2017-06-07 17:27
Yeah I tried it on our master branch and the warnings for missing translations were gone (which is what we wanted most), but sadly was unable to test it in the typescript pull request so far, but as it turned out the problem had nothing to do with typescript, so I'm quite confident everything is a-okay!

**Comment by d3viant0ne** [comment] 2017-06-10 23:15
All - `v1.0.0` is no `@latest` on npm. I'm going to leave the `@beta dist-tag` in place until next week to given anyone using that tag a chance to move to `1.0.0`.

No changes between `1.0.0-beta.1 => 1.0.0`. Should just be a matter of changing the package.

**Closed by d3viant0ne** 2017-06-10 23:15 UTC
Labels: priority: 2 (urgent), severity: 3 (broken), status: Needs repro, type: Bug
